Traceback (most recent call last):
  File "C:\Users\molly\miniforge3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\molly\miniforge3\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\molly\miniforge3\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\molly\miniforge3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\molly\miniforge3\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\molly\miniforge3\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\molly\miniforge3\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import fastf1
session = fastf1.get_session(2022, 'Monza', 'Q')
session.load(telemetry=False, laps=False, weather=False)
vettel = session.get_driver('BOT')
print(f"Pronto {vettel['FirstName']}?")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mfastf1[39;00m
[0;32m      2[0m session [38;5;241m=[39m fastf1[38;5;241m.[39mget_session([38;5;241m2022[39m, [38;5;124m'[39m[38;5;124mMonza[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mQ[39m[38;5;124m'[39m)
[0;32m      3[0m session[38;5;241m.[39mload(telemetry[38;5;241m=[39m[38;5;28;01mFalse[39;00m, laps[38;5;241m=[39m[38;5;28;01mFalse[39;00m, weather[38;5;241m=[39m[38;5;28;01mFalse[39;00m)

[1;31mModuleNotFoundError[0m: No module named 'fastf1'

